version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    ports:
      - "8000:8000"
    volumes:
      - ./data/dynamodb/data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
