AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python-sam-app-2

  Sample SAM Template for python-sam-app-2

Parameters:
  Env:
    Type: String
    Default: Local
    AllowedValues:
      - Local
      - Dev
      - Staging
      - Prod

Mappings:
  Local:
    Aws:
      Region: ap-northeast-1
      DynamoDBHost: http://dynamodb:8000
      DynamoDBBillingMode: PAY_PER_REQUEST
  Dev:
    Aws:
      Region: ap-northeast-1
      DynamoDBHost: ""
      DynamoDBBillingMode: PAY_PER_REQUEST

Globals:
  Function:
    Timeout: 29
    Runtime: python3.9
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENV: !Ref Env
        REGION: !FindInMap [!Ref Env, Aws, Region]
        DYNAMODB_HOST: !FindInMap [!Ref Env, Aws, DynamoDBHost]
        BILLING_MODE: !FindInMap [!Ref Env, Aws, DynamoDBBillingMode]

Resources:
  PackageLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 'sam/packages'
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9

  ScrapingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/bmonster/
      Handler: app.functions.scraping.lambda_handler
      Timeout: 300
      Policies:
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref PackageLayer
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: "cron(1 15 * * ? *)"

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Local
      Cors: "'*'"

  ScheduleApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/bmonster/
      Handler: app.functions.schedule.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref PackageLayer
      Events:
        GET:
          Type: Api
          Properties:
            Path: /schedule
            Method: get
            RestApiId:
              Ref: ApiGatewayApi

  ProgramReviewApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sam/bmonster/
      Handler: app.functions.program_review.lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Layers:
        - !Ref PackageLayer
      Events:
        GET:
          Type: Api
          Properties:
            Path: /programReview
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        POST:
          Type: Api
          Properties:
            Path: /programReview
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
